# Generated by Django 4.2.1 on 2023-09-21 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='imag',
            new_name='img',
        ),
    ]
