# Generated by Django 4.2.1 on 2023-10-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_newsitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='headline',
            field=models.CharField(max_length=500),
        ),
    ]
