# Generated by Django 4.2.1 on 2023-10-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_news_alter_newsitem_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
